# Generated by Django 3.1 on 2020-09-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passwrod1',
            field=models.CharField(default='adminadmin', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='passwrod2',
            field=models.CharField(default='adminadmin', max_length=20),
        ),
    ]
